spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounting_onboarding_test
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop

  flyway:
    enabled: true

invitation:
  expiration:
    enabled: false